# Generated by Django 5.2.10 on 2026-01-21 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_transacao_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.subcategoria'),
        ),
    ]
